### ISSUE TITLE
static handler for home page doesn't work

### ISSUE THREAD

**Issue by snarfed** [XeoN-GHMB/app_server#5]
Hi again! I haven't dug into this one yet, but I figured I'd report it first. Evidently `static_files` isn't supported for the home page? eg this returns a 404:

```yaml
- url: /
  static_files: static/index.html
  upload: static/index.html
```

...but if you add any path to `url`, like this, it works.

```yaml
- url: /x
  static_files: static/index.html
  upload: static/index.html
```
